### ISSUE TITLE
玩家登入时插件报错

### ISSUE THREAD

**Issue by iLunarCraft** [liaojinmin/GeekCosmeticsWiki#2]
你好 我在使用GeekCosmetics时发生错误
只要玩家登入伺服器就会跳这个错误
1.17.1版本
[latest.log](https://github.com/liaojinmin/GeekCosmeticsWiki/files/13544076/latest.log)

**Comment by liaojinmin** [comment]
下版本一起更新

**Comment by iLunarCraft** [comment]
感谢

**Comment by liaojinmin** [comment]
已修复
